on: [push]

jobs:
  test_vpns:
    runs-on: ubuntu-latest
    name: Testing VPNs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull docker
        run: docker pull ghcr.io/heig-srx-2024/srx-labo-5
      - name: Test VPNs
        run: test/runit.sh
